# Generated by Django 5.1.7 on 2025-04-30 10:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototypes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prototype',
            name='supervisor',
        ),
        migrations.AddField(
            model_name='prototype',
            name='project_link',
            field=models.URLField(blank=True, help_text='Link to the project repository or website.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='prototype',
            name='research_group',
            field=models.CharField(blank=True, choices=[('smart_elecrtonics', 'Smart Electronics System Development Management'), ('cyber', 'Cyber Security and Privacy'), ('ai', 'AI and Complexity System'), ('wireless_mobile_computing', 'Wireless and Mobile Computing'), ('mathematical_modeling', 'Mathematical Modeling and Computational Science')], max_length=50, null=True, verbose_name='Research Group'),
        ),
        migrations.AddField(
            model_name='prototype',
            name='supervisors',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role__in': ['staff', 'admin']}, related_name='supervising_prototypes', to=settings.AUTH_USER_MODEL),
        ),
    ]
